// <auto-generated />
using System;
using AlAshmar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlAshmar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Hadith", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chapter")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Hadiths", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Halaqa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HalaqaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Halaqas", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GivenByTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<Guid>("SmesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClassId");

                    b.HasIndex("EventId");

                    b.HasIndex("GivenByTeacherId");

                    b.HasIndex("StudentId", "SmesterId", "ClassId");

                    b.ToTable("Points", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.PointCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("PointCategories", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Semesters", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Common.AllowableExtension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExtName")
                        .IsUnique();

                    b.ToTable("AllowableExtensions", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Common.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExtensionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("SafeName");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Common.ContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowMultipleResponses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FontFamily")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("HalaqaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimerMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByManagerId");

                    b.HasIndex("CreatedByTeacherId");

                    b.HasIndex("HalaqaId");

                    b.ToTable("Forms", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResponseId");

                    b.ToTable("FormAnswers", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormAnswerSelectedOption", b =>
                {
                    b.Property<Guid>("FormAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormQuestionOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FormAnswerId", "FormQuestionOptionId");

                    b.HasIndex("FormAnswerId");

                    b.HasIndex("FormQuestionOptionId");

                    b.ToTable("FormAnswerSelectedOptions", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColumnSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(12);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FontFamily")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LabelColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormQuestions", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("FormQuestionOptions", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("RespondedByStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RespondedByTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("RespondedByStudentId");

                    b.HasIndex("RespondedByTeacherId");

                    b.ToTable("FormResponses", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Managers.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Managers.ManagerAttachment", b =>
                {
                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ManagerId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("ManagerAttachments", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Managers.ManagerContactInfo", b =>
                {
                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ManagerId", "ContactInfoId");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("ManagerContactInfos", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.ClassStudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "ClassId");

                    b.ToTable("ClassStudentEnrollments", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalityNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NationalityNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentAttachment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("StudentAttachments", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassStudentId", "StartDate", "EndDate");

                    b.ToTable("StudentAttendances", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentClassEventsPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttendancePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("BehaviorPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HadithPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("QuranPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("SmesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("EventId");

                    b.HasIndex("SmesterId");

                    b.HasIndex("StudentId", "SmesterId", "ClassId");

                    b.ToTable("StudentClassEventsPoints", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentContactInfo", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId", "ContactInfoId");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("StudentContactInfos", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentHadith", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HadithId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("MemorizedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("HadithId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "HadithId");

                    b.ToTable("StudentHadiths", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentQuraanPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("MemorizedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "PageNumber");

                    b.ToTable("StudentQuraanPages", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.ClassTeacherEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMainTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId", "ClassId");

                    b.ToTable("ClassTeacherEnrollments", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalityNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NationalityNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.TeacherAttachment", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeacherId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("TeacherAttachments", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.TeacherAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassTeacherId", "StartDate", "EndDate");

                    b.ToTable("TeacherAttendances", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.TeacherContactInfo", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeacherId", "ContactInfoId");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("TeacherContactInfos", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Users.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Action")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Type = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000001111"),
                            Type = "Student"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000111"),
                            Type = "Teacher"
                        });
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            HashedPassword = "$2a$11$ugm3BJebpiSW.gjw5fVcYedC2J1OsKlNdykJ6wtVJIemVYnT2rJQO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000011"),
                            UserName = "1"
                        });
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Course", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Hadith", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Book");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Halaqa", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Course", "Course")
                        .WithMany("Halaqas")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Point", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.PointCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Academic.Halaqa", "Halaqa")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "GivenByTeacher")
                        .WithMany("GivenPoints")
                        .HasForeignKey("GivenByTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "Student")
                        .WithMany("Points")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");

                    b.Navigation("GivenByTeacher");

                    b.Navigation("Halaqa");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Common.Attachment", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Common.AllowableExtension", "Extension")
                        .WithMany()
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Extension");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.Form", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Managers.Manager", "CreatedByManager")
                        .WithMany()
                        .HasForeignKey("CreatedByManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "CreatedByTeacher")
                        .WithMany()
                        .HasForeignKey("CreatedByTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Academic.Halaqa", "Halaqa")
                        .WithMany()
                        .HasForeignKey("HalaqaId");

                    b.Navigation("Course");

                    b.Navigation("CreatedByManager");

                    b.Navigation("CreatedByTeacher");

                    b.Navigation("Halaqa");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormAnswer", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Forms.FormQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Forms.FormResponse", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormAnswerSelectedOption", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Forms.FormAnswer", "FormAnswer")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("FormAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Forms.FormQuestionOption", "FormQuestionOption")
                        .WithMany()
                        .HasForeignKey("FormQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormAnswer");

                    b.Navigation("FormQuestionOption");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormQuestion", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Forms.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormQuestionOption", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Forms.FormQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormResponse", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Forms.Form", "Form")
                        .WithMany("Responses")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "RespondedByStudent")
                        .WithMany()
                        .HasForeignKey("RespondedByStudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "RespondedByTeacher")
                        .WithMany()
                        .HasForeignKey("RespondedByTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Form");

                    b.Navigation("RespondedByStudent");

                    b.Navigation("RespondedByTeacher");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Managers.Manager", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Managers.ManagerAttachment", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Common.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Managers.Manager", "Manager")
                        .WithMany("ManagerAttachments")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Managers.ManagerContactInfo", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Common.ContactInfo", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Managers.Manager", "Manager")
                        .WithMany("ManagerContactInfos")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactInfo");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.ClassStudentEnrollment", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Halaqa", "Halaqa")
                        .WithMany("ClassStudentEnrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halaqa");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.Student", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentAttachment", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Common.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "Student")
                        .WithMany("StudentAttachments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentClassEventsPoint", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Halaqa", "Halaqa")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Academic.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SmesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "Student")
                        .WithMany("StudentClassEventsPoints")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Halaqa");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentContactInfo", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Common.ContactInfo", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "Student")
                        .WithMany("StudentContactInfos")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactInfo");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentHadith", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Halaqa", "Halaqa")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Academic.Hadith", "Hadith")
                        .WithMany()
                        .HasForeignKey("HadithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "Student")
                        .WithMany("StudentHadiths")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hadith");

                    b.Navigation("Halaqa");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.StudentQuraanPage", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Halaqa", "Halaqa")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlAshmar.Domain.Entities.Students.Student", "Student")
                        .WithMany("StudentQuraanPages")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Halaqa");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.ClassTeacherEnrollment", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Academic.Halaqa", "Halaqa")
                        .WithMany("ClassTeacherEnrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "Teacher")
                        .WithMany("ClassTeacherEnrollments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halaqa");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.Teacher", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Users.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedUser");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.TeacherAttachment", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Common.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "Teacher")
                        .WithMany("TeacherAttachments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.TeacherContactInfo", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Common.ContactInfo", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Teachers.Teacher", "Teacher")
                        .WithMany("TeacherContactInfos")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactInfo");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("AlAshmar.Domain.Entities.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlAshmar.Domain.Entities.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Course", b =>
                {
                    b.Navigation("Halaqas");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Halaqa", b =>
                {
                    b.Navigation("ClassStudentEnrollments");

                    b.Navigation("ClassTeacherEnrollments");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Academic.Semester", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.Form", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Forms.FormResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Managers.Manager", b =>
                {
                    b.Navigation("ManagerAttachments");

                    b.Navigation("ManagerContactInfos");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Students.Student", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("StudentAttachments");

                    b.Navigation("StudentClassEventsPoints");

                    b.Navigation("StudentContactInfos");

                    b.Navigation("StudentHadiths");

                    b.Navigation("StudentQuraanPages");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Teachers.Teacher", b =>
                {
                    b.Navigation("ClassTeacherEnrollments");

                    b.Navigation("GivenPoints");

                    b.Navigation("TeacherAttachments");

                    b.Navigation("TeacherContactInfos");
                });

            modelBuilder.Entity("AlAshmar.Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
